### ISSUE TITLE
Can the language server be updated?

### ISSUE THREAD

**Issue by Tornquist** [robb-j/nova-prisma#2]
Would you be able to push a build targeting a newer version of the language server?

The updated `@relation(map: "...")` and `@unique(map: "...")` syntax is throwing errors all over my schema.

`3.1.103` is the most recent version of `@prisma/language-server`

**Comment by robb-j** [comment]
Hey, I've just pushed out v1.1.0 now, I don't think there are any breaking changes from updating the language server. Let me know if that fixes your issue!

**Comment by Tornquist** [comment]
It's looking good! Thank you!
