### ISSUE TITLE
Can the language server be updated?

### ISSUE THREAD

**Issue by avasilic** [robb-j/nova-prisma#4]
The extension is highlighting `metrics` as not being a valid preview feature.

**Comment by robb-j** [comment]
@net-tech  I've just pushed out `v1.3.0` which upgrades the language server can you give it a try and check everything is working ok? The formatter seems a bit off but I think that is a [Nova bug](https://devforum.nova.app/t/nova-11-duplicates-code-after-format-document/2158/4)
